<!DOCTYPE html>
<html class="no-js ss-preload" lang="en">

<head>

   <!--- basic page needs
    ================================================== -->
   <meta charset="utf-8">
   <title>Luther - Styles</title>
   <meta name="description" content="">
   <meta name="author" content="">

   <!-- mobile specific metas
    ================================================== -->
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- CSS
    ================================================== -->
   <link rel="stylesheet" href="<?= $this->config->get('app.url') ?>public/assets/css/vendor.css">
   <link rel="stylesheet" href="<?= $this->config->get('app.url') ?>public/assets/css/styles.css">

   <style type="text/css" media="screen">
      .s-styles {
         padding-top: var(--vspace-5);
         padding-bottom: var(--vspace-4);
         position: relative;
      }

      .s-styles .intro h1 {
         margin-top: 0;
      }
   </style>

   <!-- favicons
    ================================================== -->
   <link rel="apple-touch-icon" sizes="180x180"
      href="<?= $this->config->get('app.url') ?>public/assets/apple-touch-icon.png">
   <link rel="icon" type="image/png" sizes="32x32"
      href="<?= $this->config->get('app.url') ?>public/assets/favicon-32x32.png">
   <link rel="icon" type="image/png" sizes="16x16"
      href="<?= $this->config->get('app.url') ?>public/assets/favicon-16x16.png">
   <link rel="manifest" href="<?= $this->config->get('app.url') ?>public/assets/site.webmanifest">

</head>

<body id="top">



   <div id="preloader">
      <div id="loader">
      </div>
   </div>


   <div class="s-pagewrap">

      <div class="circles">
         <span></span>
         <span></span>
         <span></span>
         <span></span>
         <span></span>
      </div>


      <header class="s-header">

         <div class="header-mobile">
            <span class="mobile-home-link"><a
                  href="<?= $this->config->get('app.url') ?>"><?= $this->config->get('app.name') ?></a></span>
            <a class="mobile-menu-toggle" href="#0"><span>Menu</span></a>
         </div>

         <div class="row wide main-nav-wrap">
            <nav class="column lg-12 main-nav">
               <ul>
                  <li><a href="<?= $this->config->get('app.url') ?>"
                        class="home-link"><?= $this->config->get('app.name') ?></a></li>
                  <li class="current"><a href="<?= $this->config->get('app.url') ?>">Intro</a></li>
                  <li><a href="<?= $this->config->get('app.url') ?>#intro">About</a></li>
                  <li><a href="<?= $this->config->get('app.url') ?>#styles">Works</a></li>
                  <li><a href="<?= $this->config->get('app.url') ?>#contact">Say Hello</a></li>
               </ul>
            </nav>
         </div>

      </header>
      <main class="s-content">

         @content

      </main>


      <!-- ## footer
        ================================================== -->
      <footer class="s-footer">

         <div class="row">
            <div class="column ss-copyright">
               <span>© Copyright Luther 2021</span>
               <span>Design by <a href="https://www.styleshout.com/">StyleShout</a> Distribution By <a
                     href="https://themewagon.com">Themewagon</a> </span>
            </div>

            <div class="ss-go-top">
               <a class="smoothscroll" title="Back to Top" href="#top">
                  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill-rule="evenodd" clip-rule="evenodd">
                     <path
                        d="M11 2.206l-6.235 7.528-.765-.645 7.521-9 7.479 9-.764.646-6.236-7.53v21.884h-1v-21.883z" />
                  </svg>
               </a>
            </div>
         </div>

      </footer>

   </div>


   <!-- Java Script
    ================================================== -->
   <script src="<?= $this->config->get('app.url') ?>public/assets/js/plugins.js"></script>
   <script src="<?= $this->config->get('app.url') ?>public/assets/js/main.js"></script>

</body>

</html>